services:
  - type: web
    name: charteye
    runtime: node
    buildCommand: cd charteye && npm install && npm run build
    startCommand: cd charteye && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEWS_DATA_DIR
        value: /data/news-data
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  - type: cron
    name: charteye-news-scraper
    runtime: python
    buildCommand: cd charteye && pip install -r requirements.txt
    schedule: "0 */6 * * *"
    startCommand: cd charteye && ./start-news-scraper.sh
    envVars:
      - key: NEWS_DATA_DIR
        value: /data/news-data 