services:
  - type: web
    name: charteye
    runtime: node
    rootDir: charteye
    buildCommand: ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEWS_DATA_DIR
        value: /data/news-data
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  - type: cron
    name: charteye-news-scraper
    runtime: python
    rootDir: charteye
    buildCommand: pip install -r requirements.txt
    schedule: "0 */6 * * *"
    startCommand: python3 NewsScrape.py
    envVars:
      - key: NEWS_DATA_DIR
        value: /data/news-data 