services:
  - type: web
    name: charteye
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
    autoDeploy: true

  - type: cron
    name: charteye-news-scraper
    runtime: python
    buildCommand: cd charteye && pip install -r requirements.txt
    schedule: "0 */6 * * *"
    startCommand: cd charteye && python NewsScrape.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: false 