services:
  - type: web
    name: charteye
    runtime: node
    plan: free
    rootDir: charteye
    buildCommand: npm install && NODE_ENV=production npx next build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEWS_DATA_DIR
        value: /var/data/news-data
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

  - type: cron
    name: charteye-news-scraper
    runtime: python
    rootDir: charteye
    buildCommand: pip install -r requirements.txt
    schedule: "0 */6 * * *"
    startCommand: python3 NewsScrape.py
    envVars:
      - key: NEWS_DATA_DIR
        value: /var/data/news-data 