services:
  - type: web
    name: charteye
    runtime: node
    buildCommand: npm install -g typescript && npm install --no-package-lock && npm run build
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PORT
        value: 3001
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyBV1JmWmbq9Zz78aU3PyBu2ERgvQNKDJiU
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: charteye-5be44.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: charteye-5be44
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: charteye-5be44.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "1088594164829"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: "1:1088594164829:web:c159dd2c36161e532fe1b4"
      - key: NEXT_PUBLIC_FIREBASE_DATABASE_URL
        value: https://charteye-5be44-default-rtdb.firebaseio.com
      - key: FIREBASE_PROJECT_ID
        value: charteye-5be44
      - key: FIREBASE_STORAGE_BUCKET
        value: charteye-5be44.firebasestorage.app
      - key: API_DEBUG
        value: "true"
      - key: USE_FALLBACK
        value: "true"
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: cron
    name: charteye-news-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    schedule: "0 */6 * * *"
    startCommand: python NewsScrape.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: false 