services:
  # Frontend service
  - type: web
    name: charteye-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NODE_ENV
        value: production

  # Backend service
  - type: worker
    name: charteye-backend
    runtime: node
    buildCommand: cd functions && npm install
    startCommand: cd functions && npm run serve
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: NODE_ENV
        value: production

  - type: cron
    name: charteye-news-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    schedule: "0 */6 * * *"
    startCommand: python NewsScrape.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: false 